### ISSUE TITLE
ccep/scripts unnecessary files 

### ISSUE THREAD

**Issue by GiulioCastegnaro** [dorahermes/ccep#12]
Some scripts present in the folder script of the ccep directory are not necessary anymore, since all the code needed for each atlas (Destrieux, DKT, Benson and Wang) had been merged into one script (master_lookup_allfouratlases.m).

**Comment by dorahermes** [comment]
Thank you! Can you make a pull request to fix these issues?

**Comment by dorahermes** [comment]
this is resolved by @GiulioCastegnaro with pull request #13
