### ISSUE TITLE
Adding monophasic analysis to functions/ccep_load_database.m

### ISSUE THREAD

**Issue by JaapVanDerAar** [dorahermes/ccep#37]
@GiulioCastegnaro 
Because in your analysis F01-F02 stimulation is not considered the same as F02-F01, while in my analysis it does, I think it is nice to add this option as a variable argument in the function for preprocessing. You and Dora made some slight changes for this in another script, so maybe you can add it into this function (I did a pull request for this function). 

I think there are multiple ways to create a variable parameter/argument for a function. Including parse (but I don't know how this works), or 'switch nargin with case 2 and 3', but I think it might be best to use something like, but @dorahermes might have a better suggestion: 

function [database] = ccep_load_database(database, top_path, varargin)
if isempty(varargin{1} OR varargin{1} == 'biphasic'
        STEPS FOR ANALYSIS WITH AVERAGING ALL
elseif varargin{1} == 'monophasic'
         STEPS FOR ANALYSIS WITH MONOPHASIC AVERAGING

I left some space in the function to put this into.

**Comment by JaapVanDerAar** [comment]
This is for functions/ccep_data_preprocess, not the load database as I said in the title

**Comment by GiulioCastegnaro** [comment]
I added an option to the ccep_data_preprocess function to select biphasic or monophasic stimuli. For now, there is no "default setting" included, therefore "1"(monophasic) or "2" (biphasic) must be added to the variables when using the function in question.
